FROM public.ecr.aws/lambda/provided:al2 as build
# install compiler
RUN yum install -y golang
RUN go install github.com/jteeuwen/go-bindata/...@latest
RUN go env -w GOPROXY=direct
# cache dependencies
# ADD go.mod go.sum ./
# RUN go mod download
# build
ADD . .
# RUN go generate ./schema
# RUN go build -o /main